### ISSUE TITLE
Add installation instructions to the README

### ISSUE THREAD

**Issue by Qqwy** [NorfairKing/sparep#2]
Hello there!

Sparep looks interesting, but I am not entirely clear on how to install it (for personal use, not for development).

Would it be possible to specify some installation instructions in the README?

**Comment by NorfairKing** [comment]
@Qqwy This project is not two months old. You'll need to get your hands dirty if you'd like to try it.

Usually this should work:

```
stack install autoexporter
stack install
```
using https://github.com/commercialhaskell/stack/
